#!/bin/bash
set -ex

jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz

source activate stan
python -m cmdstanpy.install_cmdstan
